In [1]:
import numpy as np

In [2]:
np.version

<module 'numpy.version' from 'C:\\Users\\param\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [4]:
np.__version__

'2.1.3'

In [5]:
my_list =[1,2,3,4,5,7]
my_list

[1, 2, 3, 4, 5, 7]

In [6]:
type(my_list)

list

In [7]:
my_list

[1, 2, 3, 4, 5, 7]

In [8]:
arr=np.array(my_list)

In [9]:
arr

array([1, 2, 3, 4, 5, 7])

In [10]:
print (type(arr))

<class 'numpy.ndarray'>


In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [18]:
np.arange(20,10)

array([], dtype=int64)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros([2,4,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros([10,10],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones(2)

array([1., 1.])

In [33]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [36]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.ones([2,5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
arr

array([1, 2, 3, 4, 5, 7])

In [39]:
rand(3,4)

NameError: name 'rand' is not defined

In [40]:
np.rand(3,5)

AttributeError: module 'numpy' has no attribute 'rand'

In [41]:
np.random.rand(5,10)

array([[0.83976219, 0.82810451, 0.21371653, 0.7964262 , 0.24449349,
        0.85385895, 0.78442462, 0.10723066, 0.17270098, 0.3328965 ],
       [0.82545921, 0.30101372, 0.19419248, 0.22504034, 0.02274346,
        0.09297053, 0.5439374 , 0.61900705, 0.92732169, 0.86405739],
       [0.77638588, 0.41691985, 0.11985568, 0.97282322, 0.3481742 ,
        0.22861933, 0.19561019, 0.79307255, 0.28622202, 0.12732701],
       [0.97238947, 0.77145292, 0.27255636, 0.64256141, 0.08419083,
        0.3377158 , 0.26821976, 0.11258903, 0.80963262, 0.4449736 ],
       [0.07306585, 0.86324999, 0.25753424, 0.87493545, 0.84866828,
        0.62428186, 0.83157847, 0.90881225, 0.89804895, 0.24835666]])

In [45]:
np.random.rand(2,3)

array([[0.50243739, 0.25158978, 0.29053975],
       [0.77723935, 0.73742472, 0.20980642]])

In [46]:
np.random.randint (4)

1

In [47]:
np.random.randint(2,4)

2

In [50]:
np.random.randint(2,4,3)

array([3, 2, 2], dtype=int32)

In [51]:
n=np.random.randint(2,10,(4,5))

In [52]:
n

array([[2, 4, 8, 2, 2],
       [6, 6, 9, 5, 5],
       [5, 5, 9, 7, 5],
       [6, 4, 4, 5, 9]], dtype=int32)

In [53]:
n[3]

array([6, 4, 4, 5, 9], dtype=int32)

In [54]:
n[2,3]

np.int32(7)

In [55]:
type(n)

numpy.ndarray

In [56]:
n[-2]

array([5, 5, 9, 7, 5], dtype=int32)

In [57]:
n[-2,3]

np.int32(7)

In [58]:
n[2,4]

np.int32(5)

In [59]:
n

array([[2, 4, 8, 2, 2],
       [6, 6, 9, 5, 5],
       [5, 5, 9, 7, 5],
       [6, 4, 4, 5, 9]], dtype=int32)

In [60]:
n[0:3]

array([[2, 4, 8, 2, 2],
       [6, 6, 9, 5, 5],
       [5, 5, 9, 7, 5]], dtype=int32)

In [61]:
n[1:3]

array([[6, 6, 9, 5, 5],
       [5, 5, 9, 7, 5]], dtype=int32)

In [63]:
n[0:3:2]

array([[2, 4, 8, 2, 2],
       [5, 5, 9, 7, 5]], dtype=int32)

In [64]:
m=np.random.randint(1,20,(5,5))

In [65]:
m

array([[14,  8, 10, 13, 16],
       [18, 16,  1,  7, 16],
       [14, 10,  1,  3,  6],
       [13, 16, 14, 19,  1],
       [11,  6, 18,  2, 12]], dtype=int32)

In [66]:
m[::-1]

array([[11,  6, 18,  2, 12],
       [13, 16, 14, 19,  1],
       [14, 10,  1,  3,  6],
       [18, 16,  1,  7, 16],
       [14,  8, 10, 13, 16]], dtype=int32)

In [67]:
m[::2]

array([[14,  8, 10, 13, 16],
       [14, 10,  1,  3,  6],
       [11,  6, 18,  2, 12]], dtype=int32)

In [68]:
m

array([[14,  8, 10, 13, 16],
       [18, 16,  1,  7, 16],
       [14, 10,  1,  3,  6],
       [13, 16, 14, 19,  1],
       [11,  6, 18,  2, 12]], dtype=int32)

In [69]:
m[0:4]

array([[14,  8, 10, 13, 16],
       [18, 16,  1,  7, 16],
       [14, 10,  1,  3,  6],
       [13, 16, 14, 19,  1]], dtype=int32)

In [70]:
m(0,4)

TypeError: 'numpy.ndarray' object is not callable

In [71]:
m[0,4]

np.int32(16)

In [72]:
m[4,4]

np.int32(12)

In [73]:
m

array([[14,  8, 10, 13, 16],
       [18, 16,  1,  7, 16],
       [14, 10,  1,  3,  6],
       [13, 16, 14, 19,  1],
       [11,  6, 18,  2, 12]], dtype=int32)

In [74]:
m[3,3]

np.int32(19)

In [75]:
m[3,-3]

np.int32(14)

In [76]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [77]:
k=np.arange(2,27).reshape(5,5)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [78]:
k=np.arange(2,27).reshape(5,5)

In [79]:
k

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [80]:
k[3:-3]

array([], shape=(0, 5), dtype=int64)